CREATE DATABASE voting_system;
USE voting_system;

CREATE TABLE regions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    region_name VARCHAR(100) NOT NULL
);

CREATE TABLE communes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    commune_name VARCHAR(100) NOT NULL,
    region_id INT,
    FOREIGN KEY (region_id) REFERENCES regions(id)
);

CREATE TABLE candidates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    candidate_name VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    user_nickname VARCHAR(255),
    rut VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    web TINYINT(1),
    tv TINYINT(1),
    social_media TINYINT(1),
    friend TINYINT(1),
    region_id INT NOT NULL,
    commune_id INT NOT NULL,
    candidate_id INT NOT NULL,
    FOREIGN KEY (region_id) REFERENCES regions(id),
    FOREIGN KEY (commune_id) REFERENCES communes(id),
    FOREIGN KEY (candidate_id) REFERENCES candidates(id)
);
INSERT INTO regions (region_name) VALUES 
('Arica y Parinacota'),
('Tarapacá'),
('Antofagasta'),
('Atacama'),
('Coquimbo'),
('Valparaíso'),
('Metropolitana de Santiago'),
('Libertador General Bernardo O''Higgins'),
('Maule'),
('Ñuble'),
('Biobío'),
('Araucanía'),
('Los Ríos'),
('Los Lagos'),
('Aysén del General Carlos Ibáñez del Campo'),
('Magallanes y de la Antártica Chilena');

INSERT INTO communes (commune_name, region_id) VALUES
('Arica', 1),
('Putre', 1),
('Camarones', 1),
('General Lagos', 1),
('Arica', 1),
('Iquique', 2),
('Alto Hospicio', 2),
('Pica', 2),
('Pozo Almonte', 2),
('Huara', 2),
('Antofagasta', 3),
('Calama', 3),
('Tocopilla', 3),
('Mejillones', 3),
('Taltal', 3),
('Copiapó', 4),
('Vallenar', 4),
('Caldera', 4),
('Chañaral', 4),
('Diego de Almagro', 4),
('La Serena', 5),
('Coquimbo', 5),
('Illapel', 5),
('Ovalle', 5),
('Salamanca', 5),
('Valparaíso', 6),
('Viña del Mar', 6),
('Quillota', 6),
('San Antonio', 6),
('Villa Alemana', 6),
('Santiago', 7),
('Puente Alto', 7),
('Maipú', 7),
('San Bernardo', 7),
('La Florida', 7),
('Rancagua', 8),
('Rengo', 8),
('San Fernando', 8),
('Santa Cruz', 8),
('Pichilemu', 8),
('Talca', 9),
('Linares', 9),
('Curicó', 9),
('Constitución', 9),
('San Clemente', 9),
('Chillán', 10),
('Bulnes', 10),
('Quillón', 10),
('San Carlos', 10),
('Yungay', 10),
('Concepción', 11),
('Los Ángeles', 11),
('Chillán Viejo', 11),
('Coronel', 11),
('Talcahuano', 11),
('Temuco', 12),
('Padre Las Casas', 12),
('Angol', 12),
('Villarrica', 12),
('Lautaro', 12),
('Valdivia', 13),
('La Unión', 13),
('Panguipulli', 13),
('Los Lagos', 13),
('Río Bueno', 13),
('Puerto Montt', 14),
('Osorno', 14),
('Castro', 14),
('Ancud', 14),
('Quellón', 14),
('Coyhaique', 15),
('Aysén', 15),
('Chile Chico', 15),
('Cochrane', 15),
('Puerto Aysén', 15),
('Punta Arenas', 16),
('Puerto Natales', 16),
('Porvenir', 16),
('Puerto Williams', 16),
('San Gregorio', 16);

INSERT INTO candidates (candidate_name) VALUES
('Manuel Blanco Encalada'),
('Ramón Freire Serrano'),
('Francisco Antonio Pinto Díaz'),
('José Joaquín Prieto Vial'),
('Manuel Bulnes Prieto'),
('Manuel Montt Torres'),
('José Joaquín Pérez Mascayano'),
('Federico Errázuriz Zañartu'),
('Agustín Eyzaguirre'),
('Aníbal Pinto Garmendia'),
('Domingo Santa María González'),
('José Manuel Balmaceda Fernández'),
('Jorge Montt Álvarez'),
('Federico Errázuriz Echaurren'),
('Emiliano Figueroa Larraín'),
('Pedro Montt Montt'),
('Ramón Barros Luco'),
('Juan Luis Sanfuentes Andonaegui'),
('Arturo Alessandri Palma'),
('Luis Enrique Sanfuentes Vergara'),
('Carlos Ibáñez del Campo'),
('Pedro Aguirre Cerda'),
('Juan Antonio Ríos Morales'),
('Gabriel González Videla'),
('Jorge Alessandri Rodríguez'),
('Eduardo Frei Montalva'),
('Salvador Allende Gossens'),
('Augusto Pinochet Ugarte'),
('Patricio Aylwin Azócar'),
('Eduardo Frei Ruiz-Tagle'),
('Ricardo Lagos Escobar'),
('Michelle Bachelet Jeria'),
('Sebastián Piñera Echenique'),
('Gabriel Boric Font');
